### ISSUE TITLE
Dividers are not being rendered.

### ISSUE THREAD

**Issue by Wolftein** [jpardogo/PagerSlidingTabStrip#31]
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorTabBackground"
        android:foreground="?android:attr/windowContentOverlay"
        android:textColor="?attr/colorTabText"
        android:textSize="13sp"
        app:pstsIndicatorColor="?attr/colorTabIndicator"
        app:pstsIndicatorHeight="5dp"
        app:pstsUnderlineColor="?attr/colorTabBottomDivider"
        app:pstsUnderlineHeight="1dp"
        app:pstsDividerColor="#FF0000"
        app:pstsShouldExpand="true"/>

**Comment by LOG-TAG** [comment]
Thanks for the bug fix!
But  when app:pstsPaddingMiddle="true"  app:pstsDividerWidth="1sp" causing divider rendering bugs , dividers not rendered correctly since pstsPaddingMiddle doesn't apply for dividers !!

case1>

    <com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:pstsPaddingMiddle="true"
        app:pstsDividerWidth="1sp"
        app:pstsDividerColor="@android:color/white" />

![device-2015-02-18-130319](https://cloud.githubusercontent.com/assets/1190344/6243802/8541df9c-b76f-11e4-8620-95ad38a0f505.png)

when we remove app:pstsPaddingMiddle="true" 

![device-2015-02-18-130522](https://cloud.githubusercontent.com/assets/1190344/6243811/9c8efba8-b76f-11e4-9673-fcc4a0855722.png)

**Comment by jpardogo** [comment]
Could you open please a new issue? Thanks
