### ISSUE TITLE
Style from `CustomTabProvider` is overwritten

### ISSUE THREAD

**Issue by Nutomic** [jpardogo/PagerSlidingTabStrip#68]
I am trying to have a single tab with a different text color. For this, I implement `CustomTabProvider` and call `TextView.setTextColor()`.

However, this change is overwritten by `updateTabStyles()`.

I suggest to change the code so, that the tab style is only applied by the library if `CustomTabProvider` is not implemented. (I will probably make a pull request for this myself).

**Comment by ouchadam** [comment]
:+1:  
for now I'm using a different `id` to `tab_title` so that `updateTabStyles()` skips

**Comment by jpardogo** [comment]
Do you think do we really need to update the library? Don´t you think it is fair enough just not using the id `R.id.psts_tab_title` in your custom tabs. 

**NOTE:** I have just prefix the xml files and id´s of the libraries for v1.0.9

**Comment by jpardogo** [comment]
After analysing the problem I am going to commit a fix:

```java
    if(!isCustomTabs) {
                    tab_title.setTextSize(TypedValue.COMPLEX_UNIT_PX, tabTextSize);
                    tab_title.setTypeface(tabTypeface, pager.getCurrentItem() == i ? tabTypefaceSelectedStyle : tabTypefaceStyle);
                    tab_title.setTextColor(tabTextColor);
   }
```

After pushing this fix, I will publish the v1.0.9

**Comment by jpardogo** [comment]
I leave it like that. If we change it someone will create another issue asking why the text and the style are not apply to the TextView title of the custom tabs. 
If you don't want the library manage your TextView title for the tab, use a **different** id than `R.id.psts_tab_title` in your tab layout.

**Comment by ataulm** [comment]
Just had a chat with @ouchadam. The problem he was facing was that he uses a custom tab layout so that a custom font can be used.

If using a _different_ ID as you suggest, it won't change the alpha of the text of tabs when one is selected/not-selected, because the class cannot find the text view. But if you do use the same ID, then many of the textview attributes are updated.

So the problem comes back to the fact that there's no selected/not selected state for the tab (#70) else this differentiation between selected/not-selected tabs can be done by us.

**Comment by ataulm** [comment]
oh seems that PR I submitted was covered by #51. If you supply a custom tab layout that doesn't use the `R.id.psts_tab_title` ID, your TextView should be untouched.

The problem remains here I think:
```java
private void updateTabStyles() {
        for (int i = 0; i < tabCount; i++) {
            View v = tabsContainer.getChildAt(i);
            v.setBackgroundResource(tabBackgroundResId);
            v.setPadding(tabPadding, v.getPaddingTop(), tabPadding, v.getPaddingBottom());
            TextView tab_title = (TextView) v.findViewById(R.id.psts_tab_title);

            if (tab_title != null) {
                ...
```

or more specifically:

```java
            v.setBackgroundResource(tabBackgroundResId);
            v.setPadding(tabPadding, v.getPaddingTop(), tabPadding, v.getPaddingBottom());
```

where it updates your tab regardless of ID. If a custom tab was supplied, the library should do no styling on the tab itself.

**Comment by ataulm** [comment]
#51 seems to use `updateSelection(int position)` (which sets the  selected state) in only one place, but there are other places where `selected(int position)` and `unselected(int position)` are used directly, meaning the selected state won't be set correctly (I think, haven't looked too long at it).

**Comment by ouchadam** [comment]
I like the idea of the custom tab provider being given all of the major callbacks for tab selection, style reseting etc

**Comment by Nutomic** [comment]
Sorry for the late reply.

I tried to use an ID different than `tab_title`. The problem with that is that no font style is applied at all. Imo it would be nice to have the default style applied, and then apply my own costumizations afterwards.

One possibility for this would be changing `updateTabStyles()` so that it's public and can be called from `getCustomTabView()`, or call it [here](https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/src/com/astuetz/PagerSlidingTabStrip.java#L247) if `CustomTabProvider` is not implemented.

I hope you undestand what I mean, otherwise I could just make a PR.

**Comment by camposbrunocampos** [comment]
Hello Guys, turns out that there is a better solution. 
You could just create a selector resource inside `res/colors/` and use it in your textColor attribute. I`ll print the code below. 
The text will change its color like a selector button, simple like that. There is no need of changing the lib.

<h3>res/color/btn</h3>
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true"
        android:color="#000000" /> 
    <item android:state_focused="true"
        android:color="@color/active_text" /> 
    <item android:color="#FFFFFF" /> 
</selector>


and here is where I use this resource in <b>bold</b>
<h3>slideFragment.xml</h3>
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <com.astuetz.PagerSlidingTabStrip
        android:id="@+id/pager_title"
        android:layout_width="match_parent"
        style="@style/PagerTitleStrip"
        android:layout_gravity="top"
        <b>android:textColor="@color/btn"</b>
        android:textSize="13sp"
        android:paddingBottom="@dimen/padding_logo"
        android:paddingTop="@dimen/padding_logo"
        app:pstsIndicatorColor="@color/border_title_strip"
        android:layout_height="@dimen/height_pager_title_strip"
        app:pstsTextColorSelected="@color/active_text" />
    <android.support.v4.view.ViewPager
        android:id="@+id/pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1">

    </android.support.v4.view.ViewPager>
</LinearLayout>

**Comment by Nutomic** [comment]
@camposbrunocampos If I understand this correct, it changes the color for all tabs. I only want to change a single tab's color (so there are different colors).

**Comment by camposbrunocampos** [comment]
@Nutomic Yes, you are right, only use this solution if you want to change the textColor for all tabs.

**Comment by jpardogo** [comment]
What about this:

```java
    private void notSelected(View tab) {
        if (tab != null) {
            TextView title = (TextView) tab.findViewById(R.id.psts_tab_title);
            if (title != null) {
                if(usingCustomTabs){
                    if(!((CustomTabProvider)pager.getAdapter()).setSelectedTabTypeface()){
                        setTitleTypeface(title,tabTypefaceStyle);
                    }
                    if(!((CustomTabProvider)pager.getAdapter()).setSelectedTextColor()){
                        setTitleTextColor(title,tabTextColor);
                    }
                }else{
                    setTitleTypeface(title, tabTypefaceStyle);
                    setTitleTextColor(title,tabTextColor);
                }
            }
        }
    }

    private void selected(View tab) {
        if (tab != null) {
            TextView title = (TextView) tab.findViewById(R.id.psts_tab_title);
            if (title != null) {
                if(usingCustomTabs){
                    if(!((CustomTabProvider)pager.getAdapter()).setSelectedTabTypeface()){
                        setTitleTypeface(title,tabTypefaceSelectedStyle);
                    }
                    if(!((CustomTabProvider)pager.getAdapter()).setSelectedTextColor()){
                        setTitleTextColor(title,tabTextColorSelected);
                    }
                }else{
                    setTitleTypeface(title, tabTypefaceSelectedStyle);
                    setTitleTextColor(title,tabTextColorSelected);
                }
            }
        }
    }
```

So if you are using custom tabs you will have the callbacks to apply your own style to the typeface or the color of the text. If you return false on your callback the default implementation will be apply.

**Comment by jpardogo** [comment]
@Nutomic 
@ouchadam 
@ataulm 
@camposbrunocampos 

What do you think?

**Comment by ataulm** [comment]
Hi @jpardogo 

For me, this feels like patching over an issue with the library - as you're starting to see, the base approach is making it difficult to satisfy the constraints from everyone using it, while still keeping it easy enough to maintain.

IMHO, I'd take a look at the base approach to styling. The main function of the library is to provide the sliding tabs, which - when clicked - change the viewpager's current item **and** when the viewpager's current item is changed, the correct tab is selected.

If the library doesn't apply any styles whatsoever to the tabs, then most of the custom requests for the library/bugs also disappear. Just ask for the layout for a tab (which you do), and treat it as the tab. You can either assume that the root is a TextView, and thus still keep `setTitle()`, or you can also ask for the ID of the view to direct `setTitle()` to (like the old SimpleCursorListAdapter from back in the day).

This is the approach @ouchadam and I have taken for our projects (we couldn't wait for this fix on this library, sorry) and the result is a much leaner class, with vastly fewer attributes, easier to maintain - though at the tradeoff that it's less tested (only has 2 projects using it) and doesn't match the feature set.

**Comment by Nutomic** [comment]
@jpardogo I agree with autaim that your approach seems overly complicated (consider if someone wants to change text size, or any of the dozen other attributes).

@ataulm I found your code [here](https://github.com/ataulm/PagerSlidingTabStrip/tree/selected_text_state), but am not so familiar with styles. Do you have any example code?

**Comment by jpardogo** [comment]
>The main function of the library is to provide the sliding tabs, which - when clicked - change the viewpager's current item and when the viewpager's current item is changed, the correct tab is selected.

In general, I completely agree with your approach. I think I wrote about it before in another issue, but maybe not for this library. The reason is that this library have a 2 strong points to achieve:

* The one you mention (No difference from the original one, both try that)
* The main reason I did this fork for. A way to style in an easy way without thinking much about it. Just place your layout and the tabs will be styled as your theme and material principals will pick up.

There are many people that won't bother going through the hassle of changing alphas, colours and styles and even less to control the selection or deselection of tabs. Basically I want to provide an easy way for people that don't know as much as a professional android developer know. It is true I don't want to forget simplicity, cleanliness and good practices but I want to find a middle way, which is exactly the challenge.

It is not that I don't want to add more attributes to the library but I think I would like to maintain the ones we have: 

* `pstsTextAlpha` Set the text alpha transparency for non selected tabs. Range 0..255. 150 is it's default value. It WON'T be used if textColor is defined in the layout. If textColor is NOT defined, It will be applied to the non selected tabs.
* `pstsTextColorSelected` Set selected tab text color. textPrimaryColor will be it's default color value.
* `pstsTextStyle` Set the text style, default normal on API 21, bold on older APIs.
* `pstsTextSelectedStyle` Set the text style of the selected tab, default normal on API 21, bold on older APIs.
* `pstsTextFontFamily` Set the font family name. Default sans-serif-medium on API 21, sans-serif on older APIs.
* `pstsPaddingMiddle ` If true, the tabs start at the middle of the view (Like Newsstand google app).

```java
    //This actually solve the issue for custom fonts, we don't need callbacks or custom tabs
    public void setTypeface(Typeface typeface, int style, int selectedStyle) {
        this.tabTypeface = typeface;
        this.tabTypefaceSelectedStyle = selectedStyle;
        this.tabTypefaceStyle = style;
        updateTabStyles();
    }
```
A part of this attributes and the way we use the already existing ones, the library is the same as the original.

**Comment by ataulm** [comment]
@Nutomic the library we're using is not publicly released - the link you found is a fork of this library.

@jpardogo a default style is perfect for those that don't want to provide their own, and I agree with you on this! :dancer: I would ensure that the default style isn't given any unnecessary advantages just because it's part of this library - i.e. keep the sliding tabs functionality entirely separate from the styles you supply, and **force it to go through the same mechanism that other users of the library have to go through to style their tabs**.

This would mean no modifying the tabs after they are inflated - limiting yourself to changing the tabs' states (selected/focused/checked etc.). For example, the default implementation could inflate a tab as you do, but all the styles for that should be isolated in the layout.xml of the tab you inflate.

> This last function actually solve the issue for custom fonts, although we can keep just callbacks as selected and unselected return true or false.

If you saw code that was flipping the styles/appearance of a View in a callback based on the view's state, would that appear fishy to you? I wouldn't (and thus didn't) use a library that forced me to programmatically set styles where elsewhere in my app I'm using widgets that react correctly to view states (ListView, RecyclerView, Buttons, EditText, etc.).

**Comment by jpardogo** [comment]
@Nutomic @ataulm 
After reviewing our old conversation on this [issue](https://github.com/jpardogo/PagerSlidingTabStrip/pull/70#issuecomment-75384047), and after thinking of the pros and cons, I think we have arrived to a good middle point. 
So I have just pushed (d8f1a1efc4c573f16e684c49f03105d627226f5a) a new branch. This is a massive API change but I think It is for good (Even if the people complain too much :P ).
We still can clean and refactor several things but first thing would be to agree in the functionality and merge with dev.

Cheers for your help! Really appreciate it. :+1:

**Comment by Nutomic** [comment]
Actually, I misunderstood code @jpardogo. What we need is not a seperate style for the active tab, but for the first tab (and only under some conditions).

So I think the only option for that would be an optional callback where I can set the style myself.

**Comment by jpardogo** [comment]
What do you mean separate style for active tab or first tab? Now we are working with selectors and view states, no modifying the tabs after they are inflated and adding callbacks for custom tabs (selected/deselected)... did you read the code for the branch [iss68_iss70](https://github.com/jpardogo/PagerSlidingTabStrip/tree/iss68_iss70)?  and this [commit](https://github.com/jpardogo/PagerSlidingTabStrip/commit/d8f1a1efc4c573f16e684c49f03105d627226f5a)? clone the branch and try the code.

**Comment by jpardogo** [comment]
iss68_iss70 merged on dev. It will be in for the next release 679a74e5d0cf45674efe0985fc706f0015ec22d1
