### ISSUE TITLE
BUG: Incorrect default text color

### ISSUE THREAD

**Issue by TakumaMochizuki** [jpardogo/PagerSlidingTabStrip#78]
I try to update version 1.0.9

android:textColorPrimary value (from your theme) will be applied automatically to the tab's text color (Selected tab with 255 alpha and non selected tabs with 150 alpha) , underlineColor, dividerColor and indicatorColor, if the values are not define on the xml layout.

I found the selected tab color was opposite of non selected tab color.

**Comment by damianflannery** [comment]
+1

**Comment by jpardogo** [comment]
Could you please add code and screen captures to have an idea of what is happening in here?

**Comment by damianflannery** [comment]
Sure, here is a screenshot of what it should look like:

https://dl.dropboxusercontent.com/u/27007357/tictrac/fixed.png

N.b. a quick fix is to add the following attributes directly to the PagerSlidingTitleStrip tag 

android:textColor="#99FFFFFF"
pst:pstsTextColorSelected="@android:color/white"
pst:pstsIndicatorColor="@android:color/white"

Without these, it now looks like (since v1.0.5 I think):

https://dl.dropboxusercontent.com/u/27007357/tictrac/broken.png

**Comment by jpardogo** [comment]
Please can you post your theme and you xml layout? The example works so it should work for you too.

**Comment by TakumaMochizuki** [comment]
I'm sorry too late to reply, please wait to post screen shot with xml, and I found another issue is when I use the setTextColor(Color)

e.g.
```
tabs.setTextColor(Color.WHITE);
```

to change tab text color programmatically, but the similar situation has occured.

<img src="http://i.imgur.com/nq2y87x.png" width="250">

**Comment by jpardogo** [comment]
The README file explain which the default colours are and what you have to do to change them. 
I don't see it as an issue.
The API changed to deal with alpha performance issues in android. For more information about it, please read the closed PR's and issues.
Thanks.
